services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_crud_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  postgres_data:
    driver: local

networks:
  nestjs_network:
    driver: bridge
